### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by randomev** [XaroRSA/DataDownload#1]
It seems that it has some issues with "timestore_adminkey" - variable. I'm getting these errors when trying this module with my local emoncms installation. Emoncms shows DataDownload just fine at upper menu but it immediately gives following errors when I move to that tab:

/var/www/emoncms/Modules/feed/feed_model.php on line 26

Notice: Undefined variable: timestore_adminkey in /var/www/emoncms/Modules/feed/feed_model.php on line 41

Warning: Missing argument 2 for Feed::__construct(), called in /var/www/emoncms/Modules/DataDownload/DataDownload_controller.php on line 10 and defined in /var/www/emoncms/Modules/feed/feed_model.php on line 26

Notice: Undefined variable: timestore_adminkey in /var/www/emoncms/Modules/feed/feed_model.php on line 41

Fatal error: Call to undefined method Feed::get_timevalue_firstlast() in /var/www/emoncms/Modules/DataDownload/DataDownload_controller.php on line 40
Download

**Comment by XaroRSA** [comment]
Ah yes, this would happen. Im using a older version of EMONCMS that doesnt have the timestore database addition. Will need to look at this to fix, but shouldnt be a problem :DD

**Comment by randomev** [comment]
I just got it working with following crude changes;

DataDownload_controller.php:

function DataDownload_controller()
{
    global $mysqli, $user, $session, $route;

```
    global $feed;
    global $timestore_adminkey;

    require "Modules/feed/feed_model.php";
    $feed = new Feed($mysqli, $timestore_adminkey);
```

and as there was no get_timevalue_firstlast() in feed I just overrided it;

$FirstLastDateTime=array("", "")
$calenderObjects = $filetest->Init_Calender($FirstLastDateTime);

and in DataDownload_model.php:

```
    public function Init_Calender($FirstLastDateTime)
    {

      $datefirst= gmdate("Y-m-d", strtotime("-1 months")); #, $FirstLastDateTime[0]);
      $datelast= gmdate("Y-m-d", strtotime("+1 days")); #, $FirstLastDateTime[1]);
```

I'm now able to download last month values - sort of. I still can't get any calendars if I click on calendar icon - nothing happens (I have tried both Safari and Chrome).

But most importantly I still don't get all the values I need. For example on 12 Nov 2013 I see that I have about 3.5 kW from 8:20 to 9:50 and then many individual few second spikes after that. This is ok as my load behaves that way. It is not exported in full resolution to Excel e.g.. I'm missing much of that detail - it only has about 10 sample points between 7:39 and 15:06. Please see the screenshot I'm attaching - on right is how my data looks like when viewed from emoncms, and on the left you can see what was exported to Excel.

![datadownloadexcel](https://f.cloud.github.com/assets/541276/1581940/8976bdb0-51e2-11e3-94cf-ce9026bac917.png)

**Comment by XaroRSA** [comment]
The First-Last Function was something I made, could be that its still inside my Feeds module.
I havnt looked at this in a while, and wont get round it right now.
